cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'


# CLI stuff
brew 'ack'
brew 'ag'
brew 'binutils'
brew 'coreutils'
brew 'cv'
brew 'dfc'
brew 'dialog'
brew 'fasd'
brew 'fzf'
brew 'gawk'
brew 'go'
brew 'hh'
brew 'htop'
brew 'httpie'
brew 'jq'
brew 'mc'
brew 'n'
brew 'ncdu'
brew 'nmap'
brew 'postgresql'
brew 'pv'
brew 'readline'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tig'
brew 'tree'
brew 'unrar'
brew 'vcsh'
brew 'watch'
brew 'wget'

# brew 'homebrew/x11/diffutils'
# brew 'ed --default-names'
# brew 'findutils --with-default-names'
# brew 'gnu-indent --with-default-names'
# brew 'gnu-sed --with-default-names'
# brew 'gnu-tar --with-default-names'
# brew 'gnu-which --with-default-names'
# brew 'gnutls'
# brew 'grep --with-default-names'
# brew 'wdiff --with-gettext'

# GUI stuff
cask 'appcleaner'
cask 'applepi-baker'
cask 'atom'
cask 'atom'
cask 'cdock'
cask 'cronnix'
cask 'disk-inventory-x'
cask 'diskwave'
cask 'firefox'
cask 'fluid'
cask 'google-chrome'
cask 'google-chrome'
cask 'iterm2'
cask 'launchcontrol'
cask 'mapbox-studio'
cask 'menumeters'
cask 'monolingual'
cask 'onyx'
cask 'sdformatter'
cask 'seashore'
cask 'seashore'
cask 'sequel-pro'
cask 'slack'
cask 'smartgit'
cask 'sourcetree'
cask 'spectacle'
cask 'steam'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmission'
cask 'vlc'
cask 'wireshark'
cask 'xquartz'
