#!/usr/bin/env bash

dir-info () {
  local dirs=`find . -maxdepth 1 -mindepth 1 -type d | wc -l`
  local files=`find . -maxdepth 1 -mindepth 1 -type f | wc -l`
  local total=`find . -maxdepth 1 -mindepth 1 | wc -l`
  #echo -e "$total items ($dirs dirs| $files files)"

  #local total=`memoize fd . $PWD | wc -l`
  echo -e "✨ $dirs directories, $files files, $total total"
  #echo -e "`files.last_modified_directory`"
}

# Automatically list directory contents on `cd`.
auto-cd () {
  emulate -L zsh;
  # explicit sexy ls'ing as aliases arent honored in here.
  #hash gls >/dev/null 2>&1 && CLICOLOR_FORCE=1 gls -AFh --color --group-directories-first || ls -A
  hr -
  dir-info
  # echo
  exa -a --group-directories-first
  [ -f "package.json" ] && cs package.json

  echo
  [ -d ".git" ] && git recent | sed 's/^[[:space:]]*//'

  # echo
}

chpwd_functions=( auto-cd $chpwd_functions )
